require("user.plugin_config.nvim-tree")
require("user.plugin_config.toggleterm")
require("user.plugin_config.lualine")
require("user.plugin_config.treesitter")
require("user.plugin_config.neodev")
require("user.plugin_config.mason")
require("user.plugin_config.lsp")
require("user.plugin_config.nvim-cmp")
require("user.plugin_config.telescope")
require("user.plugin_config.dap")
--require("user.plugin_config.omnisharp")
--require("user.plugin_config.neodev")

